AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A demonstration of serverless producer-consumer use case using AWS Lambda and AWS Kinesis Data Stream

Resources:
  # Define an AWS Kinesis Data Stream
  KinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: "testDataSream"
      ShardCount: 1

  # Define a Lambda function as an application producer
  ProducerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: producer/
      Runtime: python3.9
      Handler: producer-function.lambda_handler
      Environment:
        Variables:
          KINESIS_STREAM: "testDataSream"
      Policies: 
      - AWSLambdaKinesisExecutionRole
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: !GetAtt KinesisStream.Arn
            StartingPosition: LATEST
            BatchSize: 100

  # Define a Lambda function as an application consumer
  ConsumerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: consumer/
      Runtime: python3.9
      Handler: consumer-function.lambda_handler
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: !GetAtt KinesisStream.Arn
            StartingPosition: LATEST
            BatchSize: 100
            
Outputs:
  # Kinesis Data Stream name for data producers to use
  KinesisStream:
    Description: Kinesis Data Stream name
    Value: !Ref KinesisStream
  ProducerFunction:
    Description: ProducerFunction ARN
    Value: !Ref ProducerFunction
  ConsumerFunction:
    Description: ConsumerFunction ARN
    Value: !Ref ConsumerFunction