AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Centralized API

Globals:
  # Create a 
  Api:
    Auth:
      ApiKeyRequired: true
      UsagePlan:
        CreateUsagePlan: PER_API # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-api-apiusageplan.html

Resources:
  ## Centralized primary API
  PrimaryApi:
    Type: AWS::Serverless::Api
    DependsOn:
      - ReportingApi
      - UserManagementApi
    Properties:
      Description: Centralized API
      StageName: Prod
      EndpointConfiguration:
        Type: REGIONAL
      Auth:
        ApiKeyRequired: false
        UsagePlan:
          CreateUsagePlan: NONE
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: './api.yaml'
        
  ## Reporting application API Endpoint
  ReportingApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: Reporting API
      Description: Reporting API
      StageName: Prod
      EndpointConfiguration:
        Type: REGIONAL
                  
  ## User management application API Endpoint
  UserManagementApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: User Management API
      Description: User Management API
      StageName: Prod
      EndpointConfiguration:
        Type: REGIONAL
                  
  ## Reporting application Lambda function
  ReportingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: nodejs14.x
      CodeUri: src
      Environment:
        Variables:
          LOCATION: "Response from reporting application"
      Events:
        RestApi:
          Type: Api
          Properties:
            RestApiId: !Ref ReportingApi
            Method: GET
            Path: /
                  
  ## User management Lambda function
  UserManagementFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: nodejs14.x
      CodeUri: src
      Environment:
        Variables:
          LOCATION: "Response from user management application"
      Events:
        RestApi:
          Type: Api
          Properties:
            RestApiId: !Ref UserManagementApi
            Method: GET
            Path: /
  
Outputs:
  ReportingEndpoint:
    Description: Reporting API endpoint
    Value: !Sub "https://${ReportingApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  UserManagementEndpoint:
    Description: User management API endpoint
    Value: !Sub "https://${UserManagementApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  PrimaryApiEndpoint:
    Description: Primary API endpoint
    Value: !Sub "https://${PrimaryApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  ApiKey:
    Description: API Key Value
    Value: !GetAtt ReportingApiApiKey.APIKeyId