AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless patterns - Lambda to EventBridge
  
Resources:
  # Define the publisher Lambda function 
  PublisherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Timeout: 3
      Runtime: nodejs12.x
      Policies:
        - Statement:
          - Effect: Allow
            # Can be scoped to an individual event bus
            Resource: '*'
            Action:
              - events:PutEvents      

Outputs:
  PublisherFunction:
    Description: PublisherFunction function name
    Value: !Ref PublisherFunction
