version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "patterns-lambda-to-sns"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-18x8jmf1fa7ob"
s3_prefix = "patterns-lambda-to-sns"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
