name: Validate Pattern Pull Request (Manual)

on:
  workflow_dispatch:
    inputs:
      prNumber:
        description: "PR Number"
        required: true

jobs:
  validate-pull-request:
    permissions: 
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      NODE_ENV: dev
      PR_NUMBER: ${{ inputs.prNumber }}
    steps:
      # Since we are manually triggering the workflow the previous checkout has the main branch. In order to checkout the branch/code of the PR
      # we need first to use the PR number to retrieve the PR SHA number. This means we need three steps to: checkout the repo,
      # run a custom script to get the SHA, and then finally checkout the PR branch
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Extract PR details
        id: extract_PR_details
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('.github/scripts/get_pr_info.js');
            await script({github, context, core});
      - name: Checkout PR code
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.extract_PR_details.outputs.headSHA }}

      - name: Get changed files using defaults
        id: changed-files
        uses: tj-actions/changed-files@v19
        with:
          separator: ","

      - run: cd scripts && ls
      - run: cd scripts && npm i

      - run: echo "MODIFIED_FILES=${{ steps.extract_PR_details.outputs.files }}" >> $GITHUB_ENV
      - run: echo "ADDED_FILES=${{ steps.changed-files.outputs.added_files }}" >> $GITHUB_ENV
      - run: echo "TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - run: echo "PR_NUMBER=${{ inputs.prNumber }}" >> $GITHUB_ENV

      - name: Validate
        run: node scripts/validate.js
        env: # Or as an environment variable
          MODIFIED_FILES: ${{ steps.changed-files.outputs.modified_files }}
          ADDED_FILES: "${{ steps.changed-files.outputs.added_files }}"
          PR_NUMBER: ${{ inputs.prNumber }}
          TOKEN: "${{ secrets.GITHUB_TOKEN }}"           
